name: Build Result

on:
  # We want pull requests to busilds (tess but not push to the simage registry
  push:
    branches:
      - 'main'
    # Only build hen important files change
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  #pull_request:
  #  branches:
  #    - 'main'
  #  # Only build when important files change
  #  paths:
  #    - 'result/**'
  #    - '.github/workflows/call-docker-build-result.yaml'
  schedule:
    # Re-run monthly to keep he imge fresh with upstream base images
    - cron: '0 12 15 * *'

jobs:
  call-docker-build:
    name: Call Docker Build
    uses: ./.github/workflows/reusable-docker-build.yaml
    permissions:
      contents: read
      packages: write # Needed to push the Docker image to ghcr.io
      pull-requests: write # Needed to create and update comments in PRs
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results 
      repository-projects: write
    secrets:
      # Only needed if with:dockerhub-enable is true below
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      # Only needed if with:dockerhub-enable is true below
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      # Required
      # Enable one or both registries
      # Tell Docker where to push.
      # Note: If Docker Hub is set to true, you must set secrets above and also add account/repo/tags below
      dockerhub-enable: true
      ghcr-enable: true
      # Required
      # A list of the account/repo names for Docker build. List should match what's enabled above
      # Defaults to:
      image-names: |
        shotmar/examplevotingapp_result
        ghcr.io/shotar95/example-voting-app-result
      # Required set rules for tagging images, based on special action syntax
      # Defaults to:
      tag-rules: |
        type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=ref,event=pr
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=raw,value=gha-${{ github.run_id }}
        
      # Path to where Docker should copy files into the image
      # Defaults to the root of the repository (.)
      context: result
      # Dockerfile alternate name. Default is Dockerfile (relative to the context path)
      # file: Containerfile
      # Build stage to target, defaults to empty, which builds to the last stage in Dockerfile
      # target:
      # Platforms to build for, defaults to linux/amd64
      # Other options: linux/amd64,linux/arm64,linux/arm/v7
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      # Create a PR comment with image tags and labels
      # Defaults to false
      # comment-enable: false