name: Build Result

on:
  # ... (rest of your configuration)

jobs:
  call-docker-build:
    name: Call Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Call Docker Build
        uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
        permissions:
          contents: read
          packages: write # Needed to push the Docker image to ghcr.io
          pull-requests: write # Needed to create and update comments in PRs
        secrets:
          # Only needed if with:dockerhub-enable is true below
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Only needed if with:dockerhub-enable is true below
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          # ... (rest of your configuration)

  debug-workspace:
    name: Debug Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Workspace
        run: |
          echo "Workspace: ${{ github.workspace }}"
          ls -lah ${{ github.workspace }}

  debug-context-contents:
    name: Debug Context Contents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Context Contents
        run: |
          ls -lah ${{ github.workspace }}/result
