name: Build Result

on:
  push:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  schedule:
    - cron: '0 12 15 * *'

jobs:
  checkout_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  call-docker-build:
    name: Call Docker Build
    runs-on: ubuntu-latest
    uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      packages: write
      pull-requests: write
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      dockerhub-enable: true
      ghcr-enable: true
      image-names: |
        shotar95/examplevotingapp_result
        ghcr.io/shotar95/example-voting-app-result
      tag-rules: |
        type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=ref,event=pr
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=raw,value=gha-${{ github.run_id }}
      context: ${{ github.workspace }}/result
      platforms: linux/amd64,linux/arm64,linux/arm/v7
